# Most common words in the English language

[OEC]
# Oxfor English Corpus

nouns = [
    time,
    person,
    year,
    way,
    day,
    thing,
    man,
    world,
    life,
    hand,
    part,
    child,
    eye,
    woman,
    place,
    work,
    week,
    case,
    point,
    government,
    company,
    number,
    group,
    problem,
    fact,
]

verbs = [
    be,
    have,
    do,
    say,
    get,
    make,
    go,
    know,
    take,
    see,
    come,
    think,
    look,
    want,
    give,
    use,
    find,
    tell 
    ask,
    work,
    seem,
    feel,
    try,
    leave,
    call,
]

adjectives = [
    good,
    new,
    first,
    last,
    long,
    great,
    little,
    own,
    other,
    old,
    right,
    big,
    high,
    different,
    small,
    large,
    next,
    early,
    young,
    important,
    few,
    public,
    bad,
    same,
    able,
]

prepositions = [
    to,
    of,
    in,
    for,
    on,
    with,
    at,
    by,
    from,
    up,
    about,
    into,
    over,
    after,
]

others = [
    the,
    and,
    a,
    that,
    I,
    it,
    not,
    he,
    as,
    you,
    this,
    but,
    his,
    they,
    her,
    she,
    or,
    an,
    will,
    my,
    one,
    all,
    would,
    there,
    their,
]